<?php
  function contenido(){
    $datos=array();
    $datos[0]="img/g3.jpg"."||"."Hataraku Saibou"."||"."Hataraku Saibou trata sobre una historia sobre ti, sobre el interior de tu cuerpo. Según varios estudios, el cuerpo humano posee unos 30 billones de células. Estas células trabajan duro cada día dentro de su mundo, que es tu cuerpo. Desde los Glóbulos Rojos que portan el oxígeno, hasta los Glóbulos Blancos que se enfrentan a las amenazas de las bacterias. ¡Conoce a los héroes y las historias que se desarrollan en tu interior! Basado en el manga de Akane Shimizu, un anime con células antropomorfas y que nos cuenta la vida diaria de nuestro propio cuerpo. ";
    $datos[1]="img/g4.jpg"."||"."En'en no Shōbōtai"."||"."Shinra Kusakabe es un joven pirocinético de tercera generación que ganó el apodo de Huellas del Diablo por su habilidad para encender sus pies a voluntad. Se une al Escuadrón Fire Force 8, que está compuesto por otros usuarios de llamas mientras trabajan para extinguir cualquier Infernal que encuentren. Cuando aparece una facción que está creando Infernales, Shinra comienza a descubrir la causa de un misterioso incendio que mató a su familia 12 años atrás. ";
    $datos[2]="img/g5.jpg"."||"."Tate no Yūsha no Nariagari"."||"."Naofumi Iwatani fue invocado en un mundo paralelo junto a otras tres personas para convertirse en los héroes de ese mundo. Cada uno de los héroes fue equipado con su propia arma legendaria cuando fueron convocados. Naofumi recibió el Escudo, el único equipo defensivo, mientras que los otros recibieron armas capaces de atacar. Debido a la falta de carisma y experiencia, Naofumi terminó con una sola compañera de equipo la cual lo traiciona.";
    $datos[3]="img/g6.jpg"."||"."Hajime no ippo"."||"."Ippo Makunouchi (幕之内 一歩 Makunouchi Ippo) es un chico muy reservado y muy tímido de 17 años que trabaja con su madre en un negocio familiar de botes para pesca llamado  tienda de pesca makunouchi  Debido a ello él nunca tiene tiempo libre para dedicarse a los deportes o hacer amigos. Un día, mientras caminaba cerca de un puente camino a casa, unos abusones de su colegio (Masahiko Umezawa es líder del grupo) le comenzaron a propinar golpes por su particular olor a lombrices, pero es salvado por un famoso boxeador llamado Mamoru Takamura (鷹村 守 Takamura Mamoru), que después de ayudarlo decide llevarlo al gimnasio donde entrena (Kamogawa Boxing Gym 鴨川ボクシングジム) mientras recupera la consciencia. Después de eso, decide animarlo un poco haciendo que de golpes a un costal de arena. Al ver que Ippo tiene talento decide prestarle unos vídeos de los mejores KO de Mike Tyson. Cuando Ippo ve estos vídeos desea ser un boxeador profesional como Takamura con el objetivo de resurgir o renacer como lo hizo Tyson y desea saber qué se siente al ser fuerte. ";
    $datos[4]="img/r1.jpg"."||"."Dr. Stone"."||"."Stone cuenta la historia de dos adolescentes, Senku y Taiju; Senku se caracteriza por ser sumamente inteligente además de pertenecer al club de química de su escuela mientras que Taiju, no es demasiado inteligente como él, pero lo compensa con su gran fuerza física y que está enamorado de una linda estudiante.";
    $datos[5]="img/r2.jpg"."||"."One Punch Man"."||"."Saitama es un poderoso superhéroe calvo que derrota fácilmente a los monstruos u otros villanos con un único golpe de su puño. Debido a esto, Saitama ha encontrado aburrida su fuerza y siempre está tratando de encontrar rivales más poderosos que le puedan igualar.";
    $datos[6]="img/r3.jpg"."||"."Assassination Classroom"."||"."El Gobierno japonés encarga una importante misión a los alumnos de la clase 3-E: deben destruir a su nuevo tutor, una poderosa criatura tentaculada que planea destruir el planeta el día de la graduación. Para ayudarlos en su cometido, el mismo profesor Korosensei les enseñará todo lo necesario para acabar con él antes de que lo hagan los crueles mercenarios que van llegando al aula.";
    $datos[7]="img/r4.jpg"."||"."Darling in the Franxx"."||"."Dentro de estas ciudades futuristas, niños y niñas son entrenados para pilotar robots gigantes llamados Franxx, sin saber nada del mundo exterior. Estos jóvenes pilotos son conocidos como parásitos y son enviados a misiones a bordo de los Franxx para combatir a misteriosos enemigos llamados Klaxosaurios.";
    $datos[8]="img/r5.jpg"."||"."Ao no Exorcist"."||"."La historia se centra en Rin Okumura, un adolescente de quince años quien junto a su hermano gemelo, Yukio, fueron criados en una iglesia por el padre Shiro Fujimoto, un exorcista. ... Rin desea convertirse en un exorcista como Shiro, con el objetivo de ser más fuerte y así poder derrotar a Satanás.";
    $datos[9]="img/r6.jpg"."||"."Tengen Toppa Gurren-Lagann"."||"."Argumento. Gurren Lagann tiene lugar en un futuro donde la Tierra está dominada por el Rey Espiral, Lord Genome, que obliga a la humanidad a vivir en aldeas subterráneas aisladas. ... Kamina anima a Simón a unirse a su banda, la Brigada Gurren, para ayudarle a cumplir su sueño de ver el mundo de la superficie.";
    return $datos;
  }
?>